/** Shared shapes for the QA workflow (dev→QA handoff + QA-authored tests). */

export interface QaTestCase {
  title: string;
  steps?: string;
  expected?: string;
}

export interface QaCriterion {
  text: string;
  met: boolean;
}

/** Posted by the developer when closing an HU (via /cerrar-hu → submit_qa_review). */
export interface QaHandoff {
  criteria: QaCriterion[];
  suggestedTests: QaTestCase[];
  executedTasks: string[];
  notes?: string;
  submittedAt: string; // ISO
  submittedById?: string;
}

/** QA's own test cases, generated by AI (and editable). */
export interface QaTests {
  tests: QaTestCase[];
  generatedAt: string; // ISO
}

export function asHandoff(value: unknown): QaHandoff | null {
  if (!value || typeof value !== 'object') return null;
  const v = value as Record<string, unknown>;
  return {
    criteria: Array.isArray(v.criteria) ? (v.criteria as QaCriterion[]) : [],
    suggestedTests: Array.isArray(v.suggestedTests) ? (v.suggestedTests as QaTestCase[]) : [],
    executedTasks: Array.isArray(v.executedTasks) ? (v.executedTasks as string[]) : [],
    notes: typeof v.notes === 'string' ? v.notes : undefined,
    submittedAt: typeof v.submittedAt === 'string' ? v.submittedAt : '',
    submittedById: typeof v.submittedById === 'string' ? v.submittedById : undefined,
  };
}

export function asQaTests(value: unknown): QaTests | null {
  if (!value || typeof value !== 'object') return null;
  const v = value as Record<string, unknown>;
  if (!Array.isArray(v.tests)) return null;
  return { tests: v.tests as QaTestCase[], generatedAt: typeof v.generatedAt === 'string' ? v.generatedAt : '' };
}

/** Render a handoff as a Markdown comment body posted to the task on close. */
export function formatQaHandoffComment(h: QaHandoff): string {
  const lines: string[] = ['## ✅ Cierre de HU — entrega a QA', ''];

  if (h.criteria.length) {
    lines.push('### Criterios de aceptación');
    for (const c of h.criteria) lines.push(`- ${c.met ? '✅' : '❌'} ${c.text}`);
    lines.push('');
  }
  if (h.suggestedTests.length) {
    lines.push('### 🧪 Pruebas de QA sugeridas');
    for (const t of h.suggestedTests) {
      const bits = [t.steps && `pasos: ${t.steps}`, t.expected && `esperado: ${t.expected}`]
        .filter(Boolean)
        .join(' · ');
      lines.push(`- **${t.title}**${bits ? ` — ${bits}` : ''}`);
    }
    lines.push('');
  }
  if (h.executedTasks.length) {
    lines.push('### 📋 Tareas ejecutadas');
    for (const t of h.executedTasks) lines.push(`- ${t}`);
    lines.push('');
  }
  if (h.notes && h.notes.trim()) {
    lines.push('### Notas / contexto');
    lines.push(h.notes.trim());
    lines.push('');
  }
  return lines.join('\n').trim();
}
